seems to be working...
was fighting an issue with `seqspec check` for a while: "AttributeError: 'dict' object has no attribute 'to_dict'", due to not missing a few !Onlist declarations prior to valid barcode filename/md5s